//defines.h
#define WRITEBYTE(WORD,BYTESTARTBITPOS,VAL) WORD=(WORD&~(0xFF<<BYTESTARTBITPOS))|(((unsigned)VAL<<BYTESTARTBITPOS))
#define SETBIT(WORD,BITPOS) WORD|=1<<BITPOS
#define READWRITE(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT)))|(((SWORD>>SBIT)&1)<<DBIT)
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
//#define WRITEBIT(WORD,BITPOS,BITLEVEL) WORD=((WORD&~(1<<BITPIOS))|(BITLEVEL<<BITPOS))
#define	WRITEBIT (WORD,BITPOS,BITLEVEL) \
		(BITLEVEL?(WORD|=1<<BITPOS):(WORD&=~(1<<BITPOS)))
#define WRITE2PORTBIT(PORTNO,BITPOS,BITLEVEL)\
		(PORTNO==0)?\
		(BITLEVEL?(IOSET0=1<<BITPOS):(IOCLR0=1<<BITPOS)):\
		(BITLEVEL?(IOSET1=1<<BITPOS):(IOCLR1=1<<BITPOS))
#define WRITENIBBLE(WORD,STARTBITPOS,VAL) WORD=((WORD&~(15<<STARTBITPOS))|(VAL<<STARTBITPOS))
#define READNIBBLE(WORD,STARTBITPOS) ((WORD>>STARTBITPOS)&15)
